const languages = {
  english: {
    home: "Home",
    Projects: "Projects",
    Dashboard: "Dashboard",
    Messages: "Messages",
    Logout: "Logout",
    Organizations: "Organizations",
    Settings: "Settings",
    Documents: "Documents",
    MyProfile: "MyProfile",
    helloWorld: "Hello World",
    goodMorning: "Good Morning",
    howRU: "How are you",
    allGood: "All good",
  },
  hindi: {
    home: "घर",
    Projects: "परियोजनाओं",
    Dashboard: "डैशबोर्ड",
    Messages: "संदेशों",
    Logout: "लॉग आउट",
    Organizations: "संगठनों",
    Settings: "समायोजन",
    Documents: "दस्तावेज़",
    MyProfile: "मेरी प्रोफाइल",
    helloWorld: "नमस्ते दुनिया",
    goodMorning: "शुभ प्रभात",
    howRU: "क्या हाल है",
    allGood: "सब अच्छा",
  },
  gujarati: {
    home: "ઘર",
    Projects: "પ્રોજેક્ટ્સ",
    Dashboard: "ડેશબોર્ડ",
    Messages: "સંદેશાઓ",
    Logout: "લૉગ આઉટ",
    Organizations: "સંસ્થાઓ",
    Settings: "સેટિંગ્સ",
    Documents: "દસ્તાવેજો",
    MyProfile: "મારી પ્રોફાઈલ",
    helloWorld: "હેલો વર્લ્ડ",
    goodMorning: "સુપ્રભાત",
    howRU: "તમે કેમ છો",
    allGood: "બધા સારા",
  },
  marathi: {
    home: "मुख्यपृष्ठ",
    Projects: "प्रकल्प",
    Dashboard: "डॅशबोर्ड",
    Messages: "संदेश",
    Logout: "बाहेर पडणे",
    Organizations: "संघटना",
    Settings: "सेटिंग्ज",
    Documents: "कागदपत्रे",
    MyProfile: "माझे प्रोफाइल",
    helloWorld: "हॅलो वर्ल्ड",
    goodMorning: "शुभ प्रभात",
    howRU: "तू कसा आहेस",
    allGood: "सर्व चांगले आहे",
  },
};

export const languagesArray = Object.keys(languages);

export default languages;
